version: 2
jobs:
  build:
    working_directory: ~/monaco.editor
    docker:
      - image: circleci/openjdk:11-node
    steps:
      - checkout
      - attach_workspace:
          at: ~/monaco.editor
      - restore_cache:
          key: monaco.editor-{{ checksum "build.gradle.kts" }}
      - restore_cache:
          key: monaco.editor-node-modules-{{ checksum "websrc/package.json" }}
      - restore_cache:
          key: monaco.editor-repo
      - run: ./gradlew
      - run: tar -cvzf output.tar.gz -C build/mvn-repo .
      - save_cache:
          paths:
            - ~/.gradle
          key: monaco.editor-{{ checksum "build.gradle.kts" }}
      - save_cache:
          paths:
            - websrc/node_modules
          key: monaco.editor-node-modules-{{ checksum "websrc/package.json" }}
      - save_cache:
          paths:
            - build/mvn-repo
          key: monaco.editor-repo
      - store_artifacts:
          path: output.tar.gz
  trigger:
    working_directory: ~/monaco.editor
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: ./trigger_upstream.sh
workflows:
  version: 2
  build:
    jobs:
      - build
      - trigger:
          requires:
            - build
